"""Initial migration - multi-tenant profile system

Revision ID: 263761c7ae6f
Revises: 
Create Date: 2026-03-06 15:07:03.389681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '263761c7ae6f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identity_provider',
    sa.Column('idp_id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('idp_name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('idp_id'),
    sa.UniqueConstraint('idp_name')
    )
    op.create_table('tenant',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('tenant_name', sa.Text(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('avatar_preset',
    sa.Column('avatar_preset_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('asset_ref', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('avatar_preset_id')
    )
    op.create_index('ix_avatar_preset_tenant_active', 'avatar_preset', ['tenant_id', 'is_active'], unique=False)
    op.create_table('profile',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deactivated_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('deactivated_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_index('ix_profile_status', 'profile', ['status'], unique=False)
    op.create_index('ix_profile_tenant_id', 'profile', ['tenant_id'], unique=False)
    op.create_table('specialism',
    sa.Column('specialism_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('specialism_key', sa.Text(), nullable=False),
    sa.Column('specialism_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('specialism_id')
    )
    op.create_index('ix_specialism_tenant_active', 'specialism', ['tenant_id', 'is_active'], unique=False)
    op.create_index('ix_specialism_tenant_key', 'specialism', ['tenant_id', 'specialism_key'], unique=True)
    op.create_table('profile_avatar',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('avatar_source', sa.Text(), nullable=False),
    sa.Column('avatar_preset_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_asset_ref', sa.Text(), nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['avatar_preset_id'], ['avatar_preset.avatar_preset_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.profile_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_table('profile_display',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=False),
    sa.Column('display_name_normalized', sa.Text(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.profile_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_index('ix_profile_display_normalized', 'profile_display', ['tenant_id', 'display_name_normalized'], unique=False)
    op.create_table('profile_identity',
    sa.Column('profile_identity_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('idp_id', sa.SmallInteger(), nullable=False),
    sa.Column('idp_tenant_subject', sa.Text(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['idp_id'], ['identity_provider.idp_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.profile_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_identity_id')
    )
    op.create_index('ix_profile_identity_idp_subject', 'profile_identity', ['idp_id', 'idp_tenant_subject'], unique=True)
    op.create_index('ix_profile_identity_tenant_profile', 'profile_identity', ['tenant_id', 'profile_id'], unique=False)
    op.create_table('profile_specialism',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('specialism_id', sa.UUID(), nullable=False),
    sa.Column('proficiency_level', sa.Text(), nullable=True),
    sa.Column('assigned_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('unassigned_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('assigned_by_profile_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by_profile_id'], ['profile.profile_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.profile_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['specialism_id'], ['specialism.specialism_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'profile_id', 'specialism_id')
    )
    op.create_index('ix_profile_specialism_profile', 'profile_specialism', ['tenant_id', 'profile_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_profile_specialism_profile', table_name='profile_specialism')
    op.drop_table('profile_specialism')
    op.drop_index('ix_profile_identity_tenant_profile', table_name='profile_identity')
    op.drop_index('ix_profile_identity_idp_subject', table_name='profile_identity')
    op.drop_table('profile_identity')
    op.drop_index('ix_profile_display_normalized', table_name='profile_display')
    op.drop_table('profile_display')
    op.drop_table('profile_avatar')
    op.drop_index('ix_specialism_tenant_key', table_name='specialism')
    op.drop_index('ix_specialism_tenant_active', table_name='specialism')
    op.drop_table('specialism')
    op.drop_index('ix_profile_tenant_id', table_name='profile')
    op.drop_index('ix_profile_status', table_name='profile')
    op.drop_table('profile')
    op.drop_index('ix_avatar_preset_tenant_active', table_name='avatar_preset')
    op.drop_table('avatar_preset')
    op.drop_table('tenant')
    op.drop_table('identity_provider')
    # ### end Alembic commands ###
