"""removed tenant_id from profile specialisms

Revision ID: bc54ced8f55e
Revises: 263761c7ae6f
Create Date: 2026-03-06 15:44:56.284961

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "bc54ced8f55e"
down_revision: Union[str, Sequence[str], None] = "263761c7ae6f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
