"""create logging tables

Revision ID: 5bccb4e25b7a
Revises: 
Create Date: 2026-04-04 18:54:49.410048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5bccb4e25b7a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_trace',
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('application_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('log_type', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('subsystem', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('logger_name', sa.String(length=150), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('autotask_ticket_id', sa.Integer(), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('status_code', sa.SmallInteger(), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('outcome', sa.String(length=50), nullable=True),
    sa.Column('duration_ms', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['request_trace.request_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('idx_app_log_endpoint_method', 'application_logs', ['endpoint', 'method'], unique=False)
    op.create_index('idx_app_log_entity', 'application_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_app_log_level', 'application_logs', ['level'], unique=False)
    op.create_index('idx_app_log_occurred', 'application_logs', ['created_at', 'occurred_at'], unique=False)
    op.create_index('idx_app_log_profile_id', 'application_logs', ['profile_id'], unique=False)
    op.create_index('idx_app_log_request_id', 'application_logs', ['request_id'], unique=False)
    op.create_index('idx_app_log_tenant_id', 'application_logs', ['tenant_id'], unique=False)
    op.create_index('idx_app_log_type', 'application_logs', ['log_type'], unique=False)
    op.create_index(op.f('ix_application_logs_action'), 'application_logs', ['action'], unique=False)
    op.create_index(op.f('ix_application_logs_autotask_ticket_id'), 'application_logs', ['autotask_ticket_id'], unique=False)
    op.create_index(op.f('ix_application_logs_created_at'), 'application_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_application_logs_endpoint'), 'application_logs', ['endpoint'], unique=False)
    op.create_index(op.f('ix_application_logs_entity_id'), 'application_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_application_logs_entity_type'), 'application_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_application_logs_environment'), 'application_logs', ['environment'], unique=False)
    op.create_index(op.f('ix_application_logs_level'), 'application_logs', ['level'], unique=False)
    op.create_index(op.f('ix_application_logs_log_type'), 'application_logs', ['log_type'], unique=False)
    op.create_index(op.f('ix_application_logs_logger_name'), 'application_logs', ['logger_name'], unique=False)
    op.create_index(op.f('ix_application_logs_method'), 'application_logs', ['method'], unique=False)
    op.create_index(op.f('ix_application_logs_occurred_at'), 'application_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_application_logs_outcome'), 'application_logs', ['outcome'], unique=False)
    op.create_index(op.f('ix_application_logs_profile_id'), 'application_logs', ['profile_id'], unique=False)
    op.create_index(op.f('ix_application_logs_request_id'), 'application_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_application_logs_source'), 'application_logs', ['source'], unique=False)
    op.create_index(op.f('ix_application_logs_status_code'), 'application_logs', ['status_code'], unique=False)
    op.create_index(op.f('ix_application_logs_subsystem'), 'application_logs', ['subsystem'], unique=False)
    op.create_index(op.f('ix_application_logs_tenant_id'), 'application_logs', ['tenant_id'], unique=False)
    op.create_table('error_logs',
    sa.Column('error_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('subsystem', sa.String(length=100), nullable=True),
    sa.Column('logger_name', sa.String(length=150), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('action', sa.String(length=200), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('status_code', sa.SmallInteger(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('autotask_ticket_id', sa.Integer(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('error_resolution', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['request_trace.request_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('error_id')
    )
    op.create_index('idx_error_log_occurred', 'error_logs', ['occurred_at'], unique=False)
    op.create_index('idx_error_log_profile_id', 'error_logs', ['profile_id'], unique=False)
    op.create_index('idx_error_log_request_id', 'error_logs', ['request_id'], unique=False)
    op.create_index('idx_error_log_resolution', 'error_logs', ['error_resolution'], unique=False)
    op.create_index('idx_error_log_service', 'error_logs', ['service_name'], unique=False)
    op.create_index('idx_error_log_severity', 'error_logs', ['severity'], unique=False)
    op.create_index('idx_error_log_tenant_id', 'error_logs', ['tenant_id'], unique=False)
    op.create_index('idx_error_log_type', 'error_logs', ['error_type'], unique=False)
    op.create_index(op.f('ix_error_logs_action'), 'error_logs', ['action'], unique=False)
    op.create_index(op.f('ix_error_logs_autotask_ticket_id'), 'error_logs', ['autotask_ticket_id'], unique=False)
    op.create_index(op.f('ix_error_logs_endpoint'), 'error_logs', ['endpoint'], unique=False)
    op.create_index(op.f('ix_error_logs_environment'), 'error_logs', ['environment'], unique=False)
    op.create_index(op.f('ix_error_logs_error_type'), 'error_logs', ['error_type'], unique=False)
    op.create_index(op.f('ix_error_logs_logger_name'), 'error_logs', ['logger_name'], unique=False)
    op.create_index(op.f('ix_error_logs_method'), 'error_logs', ['method'], unique=False)
    op.create_index(op.f('ix_error_logs_occurred_at'), 'error_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_error_logs_profile_id'), 'error_logs', ['profile_id'], unique=False)
    op.create_index(op.f('ix_error_logs_request_id'), 'error_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_error_logs_service_name'), 'error_logs', ['service_name'], unique=False)
    op.create_index(op.f('ix_error_logs_severity'), 'error_logs', ['severity'], unique=False)
    op.create_index(op.f('ix_error_logs_status_code'), 'error_logs', ['status_code'], unique=False)
    op.create_index(op.f('ix_error_logs_subsystem'), 'error_logs', ['subsystem'], unique=False)
    op.create_index(op.f('ix_error_logs_tenant_id'), 'error_logs', ['tenant_id'], unique=False)
    op.create_table('performance_logs',
    sa.Column('perf_id', sa.UUID(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('operation_name', sa.String(length=150), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('logger_name', sa.String(length=150), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('total_duration_ms', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('db_latency_ms', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('external_api_latency_ms', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('app_logic_ms', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('memory_used_mb', sa.Float(), nullable=True),
    sa.Column('payload_size_kb', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_slow', sa.SmallInteger(), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('status_code', sa.SmallInteger(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('autotask_ticket_id', sa.Integer(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['request_trace.request_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('perf_id')
    )
    op.create_index('idx_perf_log_duration', 'performance_logs', ['total_duration_ms'], unique=False)
    op.create_index('idx_perf_log_endpoint', 'performance_logs', ['endpoint'], unique=False)
    op.create_index('idx_perf_log_memory', 'performance_logs', ['memory_used_mb'], unique=False)
    op.create_index('idx_perf_log_operation', 'performance_logs', ['operation_name'], unique=False)
    op.create_index('idx_perf_log_request_id', 'performance_logs', ['request_id'], unique=False)
    op.create_index('idx_perf_log_service', 'performance_logs', ['service_name'], unique=False)
    op.create_index('idx_perf_log_tenant', 'performance_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_performance_logs_autotask_ticket_id'), 'performance_logs', ['autotask_ticket_id'], unique=False)
    op.create_index(op.f('ix_performance_logs_endpoint'), 'performance_logs', ['endpoint'], unique=False)
    op.create_index(op.f('ix_performance_logs_environment'), 'performance_logs', ['environment'], unique=False)
    op.create_index(op.f('ix_performance_logs_logger_name'), 'performance_logs', ['logger_name'], unique=False)
    op.create_index(op.f('ix_performance_logs_memory_used_mb'), 'performance_logs', ['memory_used_mb'], unique=False)
    op.create_index(op.f('ix_performance_logs_method'), 'performance_logs', ['method'], unique=False)
    op.create_index(op.f('ix_performance_logs_occurred_at'), 'performance_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_performance_logs_operation_name'), 'performance_logs', ['operation_name'], unique=False)
    op.create_index(op.f('ix_performance_logs_perf_id'), 'performance_logs', ['perf_id'], unique=False)
    op.create_index(op.f('ix_performance_logs_profile_id'), 'performance_logs', ['profile_id'], unique=False)
    op.create_index(op.f('ix_performance_logs_request_id'), 'performance_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_performance_logs_service_name'), 'performance_logs', ['service_name'], unique=False)
    op.create_index(op.f('ix_performance_logs_source'), 'performance_logs', ['source'], unique=False)
    op.create_index(op.f('ix_performance_logs_status_code'), 'performance_logs', ['status_code'], unique=False)
    op.create_index(op.f('ix_performance_logs_tenant_id'), 'performance_logs', ['tenant_id'], unique=False)
    op.create_table('ui_click_analytics_logs',
    sa.Column('ui_click_log_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('profile_id', sa.UUID(), nullable=True),
    sa.Column('environment', sa.String(length=50), nullable=True),
    sa.Column('page_path', sa.String(length=255), nullable=True),
    sa.Column('component', sa.String(length=100), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('element_id', sa.String(length=150), nullable=True),
    sa.Column('duration_ms', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['request_trace.request_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('ui_click_log_id')
    )
    op.create_index('idx_ui_click_log_action', 'ui_click_analytics_logs', ['action_type'], unique=False)
    op.create_index('idx_ui_click_log_component', 'ui_click_analytics_logs', ['component'], unique=False)
    op.create_index('idx_ui_click_log_created', 'ui_click_analytics_logs', ['created_at'], unique=False)
    op.create_index('idx_ui_click_log_occurred', 'ui_click_analytics_logs', ['occurred_at'], unique=False)
    op.create_index('idx_ui_click_log_page_component', 'ui_click_analytics_logs', ['page_path', 'component'], unique=False)
    op.create_index('idx_ui_click_log_profile_id', 'ui_click_analytics_logs', ['profile_id'], unique=False)
    op.create_index('idx_ui_click_log_request_id', 'ui_click_analytics_logs', ['request_id'], unique=False)
    op.create_index('idx_ui_click_log_tenant_id', 'ui_click_analytics_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_ui_click_analytics_logs_action_type'), 'ui_click_analytics_logs', ['action_type'], unique=False)
    op.create_index(op.f('ix_ui_click_analytics_logs_component'), 'ui_click_analytics_logs', ['component'], unique=False)
    op.create_index(op.f('ix_ui_click_analytics_logs_created_at'), 'ui_click_analytics_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_ui_click_analytics_logs_element_id'), 'ui_click_analytics_logs', ['element_id'], unique=False)
    op.create_index(op.f('ix_ui_click_analytics_logs_environment'), 'ui_click_analytics_logs', ['environment'], unique=False)
    op.create_index(op.f('ix_ui_click_analytics_logs_occurred_at'), 'ui_click_analytics_logs', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_ui_click_analytics_logs_page_path'), 'ui_click_analytics_logs', ['page_path'], unique=False)
    op.create_index(op.f('ix_ui_click_analytics_logs_profile_id'), 'ui_click_analytics_logs', ['profile_id'], unique=False)
    op.create_index(op.f('ix_ui_click_analytics_logs_request_id'), 'ui_click_analytics_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_ui_click_analytics_logs_tenant_id'), 'ui_click_analytics_logs', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ui_click_analytics_logs_tenant_id'), table_name='ui_click_analytics_logs')
    op.drop_index(op.f('ix_ui_click_analytics_logs_request_id'), table_name='ui_click_analytics_logs')
    op.drop_index(op.f('ix_ui_click_analytics_logs_profile_id'), table_name='ui_click_analytics_logs')
    op.drop_index(op.f('ix_ui_click_analytics_logs_page_path'), table_name='ui_click_analytics_logs')
    op.drop_index(op.f('ix_ui_click_analytics_logs_occurred_at'), table_name='ui_click_analytics_logs')
    op.drop_index(op.f('ix_ui_click_analytics_logs_environment'), table_name='ui_click_analytics_logs')
    op.drop_index(op.f('ix_ui_click_analytics_logs_element_id'), table_name='ui_click_analytics_logs')
    op.drop_index(op.f('ix_ui_click_analytics_logs_created_at'), table_name='ui_click_analytics_logs')
    op.drop_index(op.f('ix_ui_click_analytics_logs_component'), table_name='ui_click_analytics_logs')
    op.drop_index(op.f('ix_ui_click_analytics_logs_action_type'), table_name='ui_click_analytics_logs')
    op.drop_index('idx_ui_click_log_tenant_id', table_name='ui_click_analytics_logs')
    op.drop_index('idx_ui_click_log_request_id', table_name='ui_click_analytics_logs')
    op.drop_index('idx_ui_click_log_profile_id', table_name='ui_click_analytics_logs')
    op.drop_index('idx_ui_click_log_page_component', table_name='ui_click_analytics_logs')
    op.drop_index('idx_ui_click_log_occurred', table_name='ui_click_analytics_logs')
    op.drop_index('idx_ui_click_log_created', table_name='ui_click_analytics_logs')
    op.drop_index('idx_ui_click_log_component', table_name='ui_click_analytics_logs')
    op.drop_index('idx_ui_click_log_action', table_name='ui_click_analytics_logs')
    op.drop_table('ui_click_analytics_logs')
    op.drop_index(op.f('ix_performance_logs_tenant_id'), table_name='performance_logs')
    op.drop_index(op.f('ix_performance_logs_status_code'), table_name='performance_logs')
    op.drop_index(op.f('ix_performance_logs_source'), table_name='performance_logs')
    op.drop_index(op.f('ix_performance_logs_service_name'), table_name='performance_logs')
    op.drop_index(op.f('ix_performance_logs_request_id'), table_name='performance_logs')
    op.drop_index(op.f('ix_performance_logs_profile_id'), table_name='performance_logs')
    op.drop_index(op.f('ix_performance_logs_perf_id'), table_name='performance_logs')
    op.drop_index(op.f('ix_performance_logs_operation_name'), table_name='performance_logs')
    op.drop_index(op.f('ix_performance_logs_occurred_at'), table_name='performance_logs')
    op.drop_index(op.f('ix_performance_logs_method'), table_name='performance_logs')
    op.drop_index(op.f('ix_performance_logs_memory_used_mb'), table_name='performance_logs')
    op.drop_index(op.f('ix_performance_logs_logger_name'), table_name='performance_logs')
    op.drop_index(op.f('ix_performance_logs_environment'), table_name='performance_logs')
    op.drop_index(op.f('ix_performance_logs_endpoint'), table_name='performance_logs')
    op.drop_index(op.f('ix_performance_logs_autotask_ticket_id'), table_name='performance_logs')
    op.drop_index('idx_perf_log_tenant', table_name='performance_logs')
    op.drop_index('idx_perf_log_service', table_name='performance_logs')
    op.drop_index('idx_perf_log_request_id', table_name='performance_logs')
    op.drop_index('idx_perf_log_operation', table_name='performance_logs')
    op.drop_index('idx_perf_log_memory', table_name='performance_logs')
    op.drop_index('idx_perf_log_endpoint', table_name='performance_logs')
    op.drop_index('idx_perf_log_duration', table_name='performance_logs')
    op.drop_table('performance_logs')
    op.drop_index(op.f('ix_error_logs_tenant_id'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_subsystem'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_status_code'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_severity'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_service_name'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_request_id'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_profile_id'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_occurred_at'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_method'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_logger_name'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_error_type'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_environment'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_endpoint'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_autotask_ticket_id'), table_name='error_logs')
    op.drop_index(op.f('ix_error_logs_action'), table_name='error_logs')
    op.drop_index('idx_error_log_type', table_name='error_logs')
    op.drop_index('idx_error_log_tenant_id', table_name='error_logs')
    op.drop_index('idx_error_log_severity', table_name='error_logs')
    op.drop_index('idx_error_log_service', table_name='error_logs')
    op.drop_index('idx_error_log_resolution', table_name='error_logs')
    op.drop_index('idx_error_log_request_id', table_name='error_logs')
    op.drop_index('idx_error_log_profile_id', table_name='error_logs')
    op.drop_index('idx_error_log_occurred', table_name='error_logs')
    op.drop_table('error_logs')
    op.drop_index(op.f('ix_application_logs_tenant_id'), table_name='application_logs')
    op.drop_index(op.f('ix_application_logs_subsystem'), table_name='application_logs')
    op.drop_index(op.f('ix_application_logs_status_code'), table_name='application_logs')
    op.drop_index(op.f('ix_application_logs_source'), table_name='application_logs')
    op.drop_index(op.f('ix_application_logs_request_id'), table_name='application_logs')
    op.drop_index(op.f('ix_application_logs_profile_id'), table_name='application_logs')
    op.drop_index(op.f('ix_application_logs_outcome'), table_name='application_logs')
    op.drop_index(op.f('ix_application_logs_occurred_at'), table_name='application_logs')
    op.drop_index(op.f('ix_application_logs_method'), table_name='application_logs')
    op.drop_index(op.f('ix_application_logs_logger_name'), table_name='application_logs')
    op.drop_index(op.f('ix_application_logs_log_type'), table_name='application_logs')
    op.drop_index(op.f('ix_application_logs_level'), table_name='application_logs')
    op.drop_index(op.f('ix_application_logs_environment'), table_name='application_logs')
    op.drop_index(op.f('ix_application_logs_entity_type'), table_name='application_logs')
    op.drop_index(op.f('ix_application_logs_entity_id'), table_name='application_logs')
    op.drop_index(op.f('ix_application_logs_endpoint'), table_name='application_logs')
    op.drop_index(op.f('ix_application_logs_created_at'), table_name='application_logs')
    op.drop_index(op.f('ix_application_logs_autotask_ticket_id'), table_name='application_logs')
    op.drop_index(op.f('ix_application_logs_action'), table_name='application_logs')
    op.drop_index('idx_app_log_type', table_name='application_logs')
    op.drop_index('idx_app_log_tenant_id', table_name='application_logs')
    op.drop_index('idx_app_log_request_id', table_name='application_logs')
    op.drop_index('idx_app_log_profile_id', table_name='application_logs')
    op.drop_index('idx_app_log_occurred', table_name='application_logs')
    op.drop_index('idx_app_log_level', table_name='application_logs')
    op.drop_index('idx_app_log_entity', table_name='application_logs')
    op.drop_index('idx_app_log_endpoint_method', table_name='application_logs')
    op.drop_table('application_logs')
    op.drop_table('request_trace')
    # ### end Alembic commands ###
